#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/index.ls -> dist/index.js ..."
./node_modules/.bin/lsc --no-header -cp src/index.ls > dist/index.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js

echo "still add deprecated rescope.js and rescope.min.js ..."
cp dist/index.js dist/rescope.js
cp dist/index.min.js dist/rescope.min.js

echo "update web assets ..."
rm -rf web/static/assets/lib/@plotdb/rescope/dev
mkdir -p web/static/assets/lib/@plotdb/rescope/dev
cp dist/* web/static/assets/lib/@plotdb/rescope/dev/
echo "done."
